# Generate docker-compose.yml file that build Dockerfile as "wordfeudcheater" container (no prefix), launched on port 80

version: '3'
services:
  wordfeudcheater:
    container_name: wordfeudcheater
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8123:80"